service: todo-backend-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  profile: serverless
  environment: 
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
    

functions:
  tasks:
    handler: index.handler
    events:
      - http:
          path: /tasks
          method: GET
          cors: true

