service: todo-backend-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  profile: serverless
  
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /tasks
          method: GET
          cors: true